### ISSUE TITLE
AttributeError: 'Job' object has no attribute 'lo'

### ISSUE THREAD

**Issue by JohnDMcMaster** [bsdphk/PyReveng3#3]
I get this when I run any of the examples. For example:

```
$ python3 examples/HP1345A/example.py 
examples/HP1345A/example.py
HP1345A graphics 122-2c8 rendered to /tmp/_.HP1345A.122.svg
HP1345A graphics 31e-400 rendered to /tmp/_.HP1345A.31e.svg
Traceback (most recent call last):
  File "examples/HP1345A/example.py", line 95, in <module>
    listing.Listing(pj, ncol=2)
  File "/home/mcmaster/doc/ext/PyReveng3/pyreveng/listing.py", line 60, in __init__
    lo = asp.lo
AttributeError: 'Job' object has no attribute 'lo'
```
Ubuntu 16.04.6, Python 3.5.2. Please let me know if you'd like any additional information

**Comment by bsdphk** [comment]
Sorry about that, I must have pushed in the middle of the rework I've been doing last week.

I just did a fresh pull and all seems to work now, apart from a couple of raw eprom images not checked into the tree.

I'm using python 3.6 but I don't think that should matter.
